### ISSUE TITLE
fails on package 'resolve'

### ISSUE THREAD

**Issue by hermanbanken** [juliangruber/native-modules#9]
'resolve' contains `node_modules/resolve/test/resolver/malformed_package_json`. The 'resolve/test' directory isn't part of installed dependencies and isn't listed in package-lock.json, so I think it is a bug that native-modules goes searching in that directory in the first place, but other than this bug, it could also include a try-catch when JSON parsing. Like:

```js
 fs.readFile(`${dir}/package.json`, (err, json) => {
      if (err) return
      let pkg;
      try {
        pkg = JSON.parse(json.toString('utf8'))
      } catch (e) {
        console.warn("Unreadable package", dir, e);
      }
      if (isNative(pkg)) {
```

```js
const isNative = pkg =>
  pkg && pkg.dependencies && (
    pkg.dependencies.bindings ||
    pkg.dependencies.prebuild ||
    pkg.dependencies.nan ||
    pkg.dependencies['node-pre-gyp'] ||
    pkg.dependencies['node-gyp-build']
  ) ||
  pkg && pkg.gypfile ||
  pkg && pkg.binary
```

**Comment by juliangruber** [comment]
https://github.com/juliangruber/native-modules/releases/tag/v2.0.0

**Comment by juliangruber** [comment]
I agree that not checking this directory in the first place would be the proper fix, due to time constraints however I went the quick way. Pull requests welcome!

**Comment by hermanbanken** [comment]
Thanks 👌 ❤️
